# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IDA.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IdaWindow(object):
    def setupUi(self, IdaWindow):
        IdaWindow.setObjectName("IdaWindow")
        IdaWindow.resize(1297, 831)
        IdaWindow.setWindowIcon(QtGui.QIcon('C:\\Users\\riyam\\PycharmProjects\\MajorProject\\IDA\\icon4.png'))
        self.centralwidget = QtWidgets.QWidget(IdaWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_screen = QtWidgets.QLabel(self.centralwidget)
        self.label_screen.setGeometry(QtCore.QRect(-20, -10, 1331, 871))
        self.label_screen.setText("")
        self.label_screen.setPixmap(QtGui.QPixmap("C:\\Users\\riyam\\PycharmProjects\\MajorProject\\gif\\abstract-background-futuristic-hud-ui-technology-sci-fi_35887-459 (1)"))
        self.label_screen.setScaledContents(True)
        self.label_screen.setObjectName("label_screen")
        self.label_sound = QtWidgets.QLabel(self.centralwidget)
        self.label_sound.setGeometry(QtCore.QRect(10, 140, 631, 91))
        self.label_sound.setText("")
        self.label_sound.setPixmap(QtGui.QPixmap("C:\\Users\\riyam\\PycharmProjects\\MajorProject\\gif\\source.gif"))
        self.label_sound.setObjectName("label_sound")
        self.pushButton_run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run.setGeometry(QtCore.QRect(1010, 580, 141, 41))
        self.pushButton_run.setStyleSheet("background-color: rgb(0, 95, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Bauhaus 93\";\n"
"")
        self.pushButton_run.setObjectName("pushButton_run")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(1010, 620, 141, 41))
        self.pushButton_exit.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Bauhaus 93\";\n"
"")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.label_robot = QtWidgets.QLabel(self.centralwidget)
        self.label_robot.setGeometry(QtCore.QRect(490, 210, 391, 351))
        self.label_robot.setText("")
        self.label_robot.setPixmap(QtGui.QPixmap("C:\\Users\\riyam\\PycharmProjects\\MajorProject\\gif\\1_9I6EIL5NG20A8se5afVmOg.gif"))
        self.label_robot.setScaledContents(True)
        self.label_robot.setAlignment(QtCore.Qt.AlignCenter)
        self.label_robot.setObjectName("label_robot")
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(770, 140, 201, 71))
        self.label_time.setText("")
        self.label_time.setPixmap(QtGui.QPixmap("C:\\Users\\riyam\\PycharmProjects\\MajorProject\\gif\\sideLiBG.png"))
        self.label_time.setScaledContents(True)
        self.label_time.setObjectName("label_time")
        self.label_date = QtWidgets.QLabel(self.centralwidget)
        self.label_date.setGeometry(QtCore.QRect(970, 140, 201, 71))
        self.label_date.setText("")
        self.label_date.setPixmap(QtGui.QPixmap("C:\\Users\\riyam\\PycharmProjects\\MajorProject\\gif\\date.png"))
        self.label_date.setScaledContents(True)
        self.label_date.setObjectName("label_date")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(580, 560, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_title.setFont(font)
        self.label_title.setText("")
        self.label_title.setPixmap(QtGui.QPixmap("C:\\Users\\riyam\\PycharmProjects\\MajorProject\\gif\\Capture-removebg-preview (2).png"))
        self.label_title.setScaledContents(True)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_description = QtWidgets.QLabel(self.centralwidget)
        self.label_description.setGeometry(QtCore.QRect(490, 620, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_description.setFont(font)
        self.label_description.setText("")
        self.label_description.setPixmap(QtGui.QPixmap("C:\\Users\\riyam\\PycharmProjects\\MajorProject\\gif\\Capture-removebg-preview (3).png"))
        self.label_description.setScaledContents(True)
        self.label_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description.setObjectName("label_description")
        self.label_codegif = QtWidgets.QLabel(self.centralwidget)
        self.label_codegif.setGeometry(QtCore.QRect(10, 160, 631, 451))
        self.label_codegif.setText("")
        self.label_codegif.setPixmap(QtGui.QPixmap("C:\\Users\\riyam\\PycharmProjects\\MajorProject\\gif\\gui8-unscreen.gif"))
        self.label_codegif.setScaledContents(True)
        self.label_codegif.setAlignment(QtCore.Qt.AlignCenter)
        self.label_codegif.setObjectName("label_codegif")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(780, 150, 171, 51))
        self.textBrowser.setAlignment(QtCore.Qt.AlignCenter)
        self.textBrowser.setStyleSheet("background: transparent;\n"
"border-radius: none;\n"
"color: white;\n"
"font-size: 20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(990, 150, 171, 51))
        self.textBrowser_2.setAlignment(QtCore.Qt.AlignCenter)
        self.textBrowser_2.setStyleSheet("background: transparent;\n"
"border-radius: none;\n" 
"color: white;\n"
"font-size: 20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        IdaWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(IdaWindow)
        QtCore.QMetaObject.connectSlotsByName(IdaWindow)

    def retranslateUi(self, IdaWindow):
        _translate = QtCore.QCoreApplication.translate
        IdaWindow.setWindowTitle(_translate("IdaWindow", "IDA"))
        self.pushButton_run.setText(_translate("IdaWindow", "RUN"))
        self.pushButton_exit.setText(_translate("IdaWindow", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IdaWindow = QtWidgets.QMainWindow()
    ui = Ui_IdaWindow()
    ui.setupUi(IdaWindow)
    IdaWindow.show()
    sys.exit(app.exec_())